package cabal;

public enum AuthState {
    CONNECTED,
    HANDSHAKED,
    RIGHT_CLIENT_VERSION,
    WRONG_CLIENT_VERSION,
    AUTHED,
    RECONNECT_WAIT,
    SERVER_SELECTED,
    CAPTCHA_VERIFIED,
    PUBLICKEY_INITIALIZED;
}
